# DISABLE NIXPACKS COMPLETELY - FORCE DOCKERFILE
[phases.setup]
nixPkgs = []
cmds = ["echo 'Nixpacks disabled - using Dockerfile'", "exit 1"]

[phases.install]
cmds = ["echo 'Nixpacks disabled - using Dockerfile'", "exit 1"]

[phases.build]
cmds = ["echo 'Nixpacks disabled - using Dockerfile'", "exit 1"]

[start]
cmd = "echo 'Use Dockerfile instead' && exit 1"
