# =========================================================================
# RAILWAY CONFIGURATION FOR BUKTI SETOR SERVICE - FORCE DOCKERFILE
# =========================================================================

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
FLASK_ENV = "production"
FLASK_DEBUG = "false"
PORT = "5002"
POPPLER_PATH = "/usr/bin"
SERVICE_NAME = "bukti-setor-ocr"
EASYOCR_MODULE_PATH = "/home/appuser/.EasyOCR"
