# =========================================================================
# RAILWAY CONFIGURATION FOR BUKTI SETOR SERVICE
# =========================================================================

[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
FLASK_DEBUG = "false"
PORT = "5002"
POPPLER_PATH = "/usr/bin"
SERVICE_NAME = "bukti-setor-ocr"
EASYOCR_MODULE_PATH = "/home/appuser/.EasyOCR"
