# =========================================================================
# RAILWAY CONFIGURATION - FORCE DOCKERFILE ONLY - NO NIXPACKS!
# =========================================================================

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"
nixpacksConfig = false
watchPatterns = ["Dockerfile", "requirements.txt"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
FLASK_ENV = "production"
FLASK_DEBUG = "false"
PORT = "8080"
POPPLER_PATH = "/usr/bin"
SERVICE_NAME = "bukti-setor-ocr"
EASYOCR_MODULE_PATH = "/home/appuser/.EasyOCR"
NIXPACKS_BUILDER = "false"
RAILWAY_DOCKER_BUILD = "true"
DISABLE_NIXPACKS = "true"
RAILWAY_DOCKERFILE_PATH = "Dockerfile"
