# =========================================================================
# RAILWAY CONFIGURATION FOR BUKTI SETOR SERVICE - FORCED DOCKERFILE
# =========================================================================

[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
FLASK_ENV = "production"
FLASK_DEBUG = "false"
PORT = "5002"
POPPLER_PATH = "/usr/bin"
SERVICE_NAME = "bukti-setor-ocr"
EASYOCR_MODULE_PATH = "/home/appuser/.EasyOCR"
NIXPACKS_NO_DEFAULT_BUILD = "true"
RAILWAY_DOCKERFILE_PATH = "Dockerfile"
