[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 10
startCommand = "gunicorn --bind 0.0.0.0:8080 --workers 1 --timeout 180 app_bukti_setor:app"

[env]
NIXPACKS_BUILD_CMD = ""
NIXPACKS_START_CMD = ""
